config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events
  resources :users
  resources :event_attendees, only: [:create, :destroy, :update]
  resources :invitations, only: [:create, :new, :destroy]
  post 'invitation/accept', :to => 'invitations#accept'
  root to: "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  scope :past, -> { where(date: ...(Date.today)) }
  scope :upcoming, -> { where(date: (Date.today)..)}

  belongs_to :creator, class_name: "User"

  has_many :event_attendees, foreign_key: "attended_event_id", dependent: :destroy
  has_many :invitations, foreign_key: "invited_event_id", dependent: :destroy

  has_many :attendees, -> { where('event_attendees.approved = ?', true) }, through: :event_attendees, source: :attendee
  has_many :not_approved_attendees, -> { where('event_attendees.approved = ?', false) }, through: :event_attendees, source: :attendee
  has_many :invited_users, through: :invitations, source: :invited_user

  validates :title, :presence => true
  validates :date, :presence => true
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :invited_user, class_name: "User"
  belongs_to :invited_event, class_name: "Event"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, foreign_key: "creator_id", class_name: "Event"

  has_many :event_attendees, foreign_key: "attendee_id", dependent: :destroy
  has_many :invitations, foreign_key: "invited_user_id", dependent: :destroy
  
  has_many :attended_events, -> { where('event_attendees.approved = ?', true) }, through: :event_attendees, source: :attended_event
  has_many :pending_attendance_events, -> { where('event_attendees.approved = ?', false) }, through: :event_attendees, source: :attended_event
  has_many :invited_events, through: :invitations, source: :invited_event

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
  def create
    @event_attendee = EventAttendee.new(event_attendee_params)

    @event_attendee.save unless EventAttendee.exists?(attendee_id: @event_attendee.attendee_id, attended_event_id: @event_attendee.attended_event_id)
    redirect_to event_path(@event_attendee.attended_event_id)
  end

  def destroy
    @event_attendee = EventAttendee.find(params[:id])
    @event_attendee.destroy
    redirect_to event_path(params[:id])
  end

  def update
    @event_attendee = EventAttendee.find(params[:id])
    invitation = Invitation.find_by(invited_event_id: @event_attendee.attended_event_id, invited_user_id: @event_attendee.attendee_id)
    invitation.destroy if invitation
    @event_attendee.update(approved: true)
    redirect_to event_path(@event_attendee.attended_event_id)
  end

  private

  def event_attendee_params
    params.require(:event_attendee).permit(:attendee_id, :attended_event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.build_creator(id: current_user.id)
    if @event.save
      redirect_to root_path
    else
      render "new"
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event
    else
      render "edit"
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to root_path
  end

  private

  def event_params
    params.require(:event).permit(:title, :date)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def new
  end

  def create
    @invitation = Invitation.new(invitation_params)
    @invitation.save
    redirect_to new_invitation_path(id: @invitation.invited_event_id)
  end

  def destroy
    @invitation = Invitation.find(params[:id])
    @invitation.destroy
    redirect_to user_path(@invitation.invited_user_id)
  end

  def accept
    @invitation = Invitation.find(params[:id])
    event_attendee = EventAttendee.find_by(attendee_id: @invitation.invited_user_id, attended_event_id: @invitation.invited_event_id)
    unless event_attendee
      event_attendee = EventAttendee.new(attendee_id: @invitation.invited_user_id, attended_event_id: @invitation.invited_event_id)
    end
    event_attendee.update(approved: true)
    @invitation.destroy
    redirect_to user_path(@invitation.invited_user_id)
  end

  private

  def invitation_params
    params.require(:invitation).permit(:invited_user_id, :invited_event_id)
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<br/>
<h1>Edit '<%= @event.title %>' Event</h1>
<br/>

<%= form_with model: @event do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :date %>
  <%= f.date_field :date, value: @event.date %>
  <%= f.submit %>
<% end %>
<%= link_to 'Delete', event_path(@event.id), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>

app/views/events/index.html.erb
<h1>Events</h1>
<%= link_to "Create An Event", new_event_path %>
<ul>
  <li>
    <h2>Upcoming events</h2>
    <ul>
      <% Event.upcoming.each do |event| %>
        <li>
          <h3><%= link_to event.title, event_path(event.id) %></h3>
          <h3><%= event.date %></h3>
        </li>
        <br/>
      <% end %>
    </ul>
  </li>
  <li>
    <h2>Past events</h2>
    <ul>
      <% Event.past.each do |event| %>
        <li>
          <h3><%= link_to event.title, event_path(event.id) %></h3>
          <h3><%= event.date %></h3>
        </li>
        <br/>
      <% end %>
    </ul>
  </li>
</ul>

app/views/events/new.html.erb
<br/>
<h1>Create an event</h1>
<br/>

<%= form_with model: @event do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :date %>
  <%= f.date_field :date, value: Date.today %>
  <%= f.submit %>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>
<h2><%= @event.date %></h2>

<% if user_signed_in? %>
  <% if current_user.created_events.ids.include?(@event.id) %>
    <h3><%= link_to "Edit Event", edit_event_path %></h3>
    <% if @event.not_approved_attendees.any? %>
      <h2>Pending requests</h2>
      <ol>
        <% @event.not_approved_attendees.each do |person| %>
          <li>
            <%= person.name %>
            <%= button_to "Accept", event_attendee_path(EventAttendee.find_by(attended_event_id: @event.id,
                                                  attendee_id: person.id).id), method: :patch %>
          </li>
        <% end %>
      </ol>
    <% end %>
    <h3><%= link_to "Invite Users", new_invitation_path(id: @event.id) %></h3>

    <% if @event.invited_users.any? %>
      <h2>A list of invited users</h2>
      <ul>
        <% @event.invited_users.each do |user| %>
          <li><%= link_to user.name, user_path(user.id) %></li>
        <% end %>
      </ul>
      <br/>
    <% end %>

  <% else %>
    <% if current_user.attended_events.ids.include?(@event.id) %>
      <%= button_to 'Not Attend', event_attendee_path(EventAttendee.find_by(attended_event_id: @event.id,
                                                attendee_id: current_user).id), method: :delete %>
    <% else %>
      <% if current_user.pending_attendance_events.ids.include?(@event.id) %>
        <%= button_to 'Cancel Attendance Request', event_attendee_path(EventAttendee.find_by(attended_event_id: @event.id,
                                                  attendee_id: current_user).id), method: :delete %>
      <% else %>
        <%= button_to 'Request Attendance', event_attendees_path("event_attendee[attendee_id]": current_user.id, 
                                              "event_attendee[attended_event_id]": @event.id), method: :post %>
      <% end %>
    <% end %>
  <% end %>
<% else %>
  <h4><%= link_to "Sign in to attend an event", new_user_session_path %></h4>
<% end %>

<h2>A list of attendees</h2>
<ul>
  <% @event.attendees.each do |attendee| %>
    <li><%= link_to attendee.name, user_path(attendee.id) %></li>
  <% end %>
</ul>

app/views/invitations/new.html.erb
<h1>Invite Users</h1>

<% event = Event.find(params[:id])%>
<ul>
  <% User.all.each do |user| %>
    <% unless event.invited_users.ids.include?(user.id) || event.attendees.ids.include?(user.id)%>
      <li>
        <%= user.name %>
        <%= button_to "Invite", invitations_path("invitation[invited_user_id]": user.id, "invitation[invited_event_id]": event.id) %>
      </li>
    <% end %>
  <% end %>
</ul>

<%= link_to "Back to the event", event_path(params[:id]) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="Header">
      <h4>
        <% if user_signed_in? %>
          <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: 'Are you sure you want to log out?'} %>
          <%= link_to "Profile", user_path(current_user.id) %>
        <% else %>
          <%= link_to "Log in", new_user_session_path %>
          <%= link_to "Sign up", new_user_registration_path %>
        <% end %>
        <%= link_to "Events", events_path %>
      </h4>
    </div>

    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h2><%= @user.name %></h2>
<% if @user.created_events.any? %>
  <h3>Created events</h3>
  <ul>
    <% @user.created_events.each do |event| %>
      <li><%= link_to event.title, event_path(event.id) %></li>
    <% end %>
  </ul>
<% end %>

<% if @user.attended_events.any? %>
  <h3>Attended events</h3>
  <ul>
    <% if @user.attended_events.where(date: ...(Date.today)).any? %>
      <li>
        <h4>Occured in the past</h4>
        <ul>
          <% @user.attended_events.where(date: ...(Date.today)).each do |event| %>
            <li><%= link_to event.title, event_path(event.id) %> (<%= event.date %>)</li>
          <% end %>
        </ul>
      </li>
    <% end %>
    <% if @user.attended_events.where(date: (Date.today)..).any? %>
      <li>
        <h4>Will occur in the future</h4>
        <ul>
          <% @user.attended_events.where(date: (Date.today)..).each do |event| %>
            <li><%= link_to event.title, event_path(event.id) %> (<%= event.date %>)</li>
          <% end %>
        </ul>
      </li>
    <% end %>
  </ul>
<% end %>

<% if @user.pending_attendance_events.any? %>
  <h3>Pending Attendance Requests</h3>
  <ol>
    <% @user.pending_attendance_events.each do |event| %>
      <li><%= link_to event.title, event_path(event.id) %></li>
    <% end %>
  </ol>
<% end %>

<br/>

<% if @user.invited_events.any? %>
  <h3>Invitations to events</h3>
  <ol>
    <% @user.invited_events.each do |event| %>
      <li>
        <%= link_to event.title, event_path(event.id) %>
        (<%= event.date %>)
        <%= button_to "accept", invitation_accept_path(id: Invitation.find_by(invited_event_id: event.id, 
                                      invited_user_id: @user.id).id) %>
        <%= button_to "decline", invitation_path(Invitation.find_by(invited_event_id: event.id, 
                                              invited_user_id: @user.id).id), method: :delete %>
      </li>
    <% end %>
  </ol>
<% end %>